import Head from 'next/head';
import { BsCircleHalf } from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from 'react-icons/ai';
import { useState } from 'react';

import Image from 'next/image';
import design from '../public/design.png';
import consult from '../public/consulting.png';

import code from '../public/code.png';
import web1 from '../public/web1.png';
import web2 from '../public/web 2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import face from '../public/cartoon-nobg.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Javier Cervera Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="bg-stone-100 px-10 md:px-20 lg-px-40 dark:bg-stone-900 ">
        <section className="min-h-screen bg ">
          {/* {NAVBAR} */}
          {/* {NAVBAR} */}
          {/* {NAVBAR} */}
          <nav className="py-10 mb-12 flex justify-between">
            <div className="rounded-sm  bg-stone-900">
              <h1 className="text-3xl text-stone-100 dark:text-stone-100 font-good ">
                J<span className="text-red-600 hvr-grow">V</span>R
              </h1>
            </div>

            <ul className="flex items-center">
              <li>
                <BsCircleHalf
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-3xl text-stone-900 dark:text-stone-100 "
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-red-600
                to-rose-800 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* {HERO} */}
          {/* {HERO} */}
          {/* {HERO} */}
          <div className="text-center p-2 m-10">
            <h2 className="text-6xl py-2  font-bold text-red-500 md:text-7xl font-coms">
              Javier Cervera
            </h2>
            <h3 className="text-2xl py-2 font-medium text-stone-900 md:text-3xl dark:text-stone-100 font-com">
              Frontend Developer
            </h3>
            <p className=" dark:text-stone-100 text-md mx-auto pt-2 leading-5  font-light text-stone-700 md:text-lg max-w-xl ">
              Freelancer providing Web Services with the latest technolgies
            </p>
            <p className="text-md dark:text-stone-100 mx-auto text-stone-900 font-light lg max-w-xl ">
              Contact me for any further inquires.
            </p>
          </div>

          {/* {Icons} */}
          <div className=" text-5xl flex justify-center gap-10 text-blue-500">
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className=" mx-auto relative bg-gradient-to-b from-red-500  to-stone-900  flex justify-center rounded-full  w-70 h-70 mt-10 overflow-hidden md:h-96 md:w-96">
            <Image
              src={face}
              className=" rounded-full "
              objectFit="cover"
              alt="developer-image"
              layout="responsive"
            />
          </div>
        </section>
        <hr className="my-5 mt-10" />
        <section>
          {/* {SERVICES} */}
          {/* {SERVICES} */}
          {/* {SERVICES} */}
          <div>
            <h3 className="text-3xl text-stone-900 font-semibold  py-1 pt-5  dark:text-white font-good">
              My Services
            </h3>
            <p className=" text-stone-900 text-md leading-8 py-2  dark:text-white ">
              Hola
            </p>
          </div>
          <div className="lg:flex gap-10">
            {/* {SERVICES} */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto "
                src={design}
                width={100}
                height={100}
                alt="developer-image"
              />
              <h3 className="text-stone-900  text-lg font-medium pt-8 pb-2  dark:text-red-600 ">
                Stuning Designs
              </h3>
              <p className="text-stone-900 pb-3 dark:text-white">
                Zombie ipsum reversus ab viral inferno nam, rick cemetery four
              </p>
              <h4 className="text-red-500 pt-4 pb-2  font-medium dark:text-white">
                Design Tools I use
              </h4>
              <p className="text-stone-700 py-1  dark:text-white">Tailwind</p>
              <p className="text-stone-700 py-1  dark:text-white">Bootstrap</p>
              <p className="text-stone-700 py-1  dark:text-white">Balsamic</p>
            </div>
            {/* {SERVICES} */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto "
                src={code}
                width={100}
                height={100}
                alt="developer-image"
              />
              <h3 className="text-stone-900  text-lg font-medium pt-8 pb-2 ">
                Stuning Designs
              </h3>
              <p className="text-stone-900 pb-3  dark:text-white">
                Zombie ipsum reversus ab viral inferno nam, rick cemetery four
              </p>
              <h4 className="text-red-500 pt-4 pb-2   font-medium  dark:text-white">
                Design Tools I use
              </h4>
              <p className="text-stone-700 py-1  dark:text-white">Tailwind</p>
              <p className="text-stone-700 py-1  dark:text-white">Bootstrap</p>
              <p className="text-stone-700 py-1  dark:text-white">Balsamic</p>
            </div>
            {/* {SERVICES} */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image
                className="mx-auto "
                src={consult}
                width={100}
                height={100}
                alt="developer-image"
              />
              <h3 className="text-stone-900  text-lg font-medium pt-8 pb-2 ">
                Stuning Designs
              </h3>
              <p className="text-stone-900 pb-3">
                Zombie ipsum reversus ab viral inferno nam, rick cemetery four
              </p>
              <h4 className="text-red-500 pt-4 pb-2 font-medium">
                Design Tools I use
              </h4>
              <p className="text-stone-700 py-1">Tailwind</p>
              <p className="text-stone-700 py-1">Bootstrap</p>
              <p className="text-stone-700 py-1">Balsamic</p>
            </div>
          </div>
        </section>
        <hr className="my-5 mt-10" />
        <section>
          <div>
            {/* {PORTFOLIO} */}
            <h3 className="text-3xl text-stone-900 font-semibold  py-1 pt-5  dark:text-white font-good">
              PORTFOLIO
            </h3>
            <p className=" text-stone-900 text-md leading-8 py-2  dark:text-white ">
              Hola
            </p>
          </div>
          <div className=" flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  grid grid-cols-1 md:grid-cols-2 ">
            {/* {web} */}
            <div className="basis-1/3 flex-1 shadow-lg">
              <Image
                src={web1}
                className=" rounded-lg object-cover   hover:scale-110 transition duration-300 ease-in-out"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                alt="developer-image"
              />
            </div>
            {/* {web} */}
            <div className="basis-1/3 flex-1 shadow-lg ">
              <Image
                src={web2}
                className=" rounded-lg object-cover   hover:scale-110 transition duration-300 ease-in-out"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                alt="developer-image"
              />
            </div>
            {/* {web} */}
            <div className="basis-1/3 flex-1 shadow-lg">
              <Image
                src={web3}
                className=" rounded-lg object-cover   hover:scale-110 transition duration-300 ease-in-out "
                width={'100%'}
                height={'100%'}
                layout="responsive"
                alt="developer-image"
              />
            </div>
            {/* {web} */}
            <div className="basis-1/3 flex-1 shadow-lg">
              <Image
                src={web4}
                className="rounded-xl object-cover   hover:scale-110 transition duration-300 ease-in-out"
                width={'100%'}
                height={'100%'}
                layout="responsive"
                alt="developer-image"
              />
            </div>
          </div>
        </section>
        <hr className="my-5 mt-10" />
      </main>
    </div>
  );
}
